version: "3"

networks:
  api_network:

services:
  api:
    build: .
    image: $API_IMAGE
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - api_network
    ports:
      - $PORT:$PORT
    restart: always
